export default [
    {
        id:1,
        conversation_id:1,
        type:0,
        status:0,
        manager_id:1,
        text:'TEST TEST TEST',
        date:1000000,
    },{
        id:2,
        conversation_id:1,
        type:0,
        status:0,
        manager_id:1,
        text:'TEST TEST TEST',
        date:10000002,
    },{
        id:3,
        conversation_id:1,
        type:0,
        status:0,
        manager_id:1,
        text:'TEST TEST TEST',
        date:10000003,
    },{
        id:4,
        conversation_id:1,
        type:0,
        status:0,
        manager_id:1,
        text:'TEST TEST TEST',
        date:10000004,
    },{
        id:5,
        conversation_id:1,
        type:0,
        status:0,
        manager_id:1,
        text:'TEST TEST TEST',
        date:10000005,
    },{
        id:6,
        conversation_id:1,
        type:0,
        status:0,
        manager_id:1,
        text:'TEST TEST TEST',
        date:10000006,
    },{
        id:7,
        conversation_id:1,
        type:0,
        status:0,
        manager_id:1,
        text:'TEST TEST TEST',
        date:10000007,
    },{
        id:8,
        conversation_id:1,
        type:0,
        status:0,
        manager_id:1,
        text:'TEST TEST TEST',
        date:10000008,
    },{
        id:9,
        conversation_id:1,
        type:0,
        status:0,
        manager_id:1,
        text:'TEST TEST TEST',
        date:10000009,
    },{
        id:10,
        conversation_id:1,
        type:0,
        status:0,
        manager_id:1,
        text:'TEST TEST TEST',
        date:100000010,
    },{
        id:11,
        conversation_id:1,
        type:0,
        status:0,
        manager_id:1,
        text:'TEST TEST TEST',
        date:101000000,
    },
];